time_budget: 60
# total running time in seconds
metric: accuracy
# can be: 'r2', 'rmse', 'mae', 'mse', 'accuracy', 'roc_auc', 'roc_auc_ovr',
# 'roc_auc_ovo', 'log_loss', 'mape', 'f1', 'ap', 'ndcg', 'micro_f1', 'macro_f1'
log_training_metric: true
task: classification
# task type
log_file_name: ${oc.select:..path.log.filepath, automl.log}
# flaml log file
seed: 7654321
# random seed
verbose: ${oc.select:..verbose, 3}
